import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  guide: [
    'guide/index',
    'guide/integrations/index',
    'guide/direct',
    'guide/bindings',
    'guide/community',
  ],
  // faq: [
  //   {
  //     type: 'autogenerated',
  //     dirName: 'faq',
  //   },
  // ],
}

export = sidebars
