import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  guide: [
    'guide/index',
    {
      type: 'category',
      label: '集成',
      link: {
        type: 'doc',
        id: 'guide/integrations/index',
      },
      items: ['guide/integrations/koishi'],
    },
    'guide/direct',
    'guide/bindings',
    'guide/community',
  ],
  // faq: [
  //   {
  //     type: 'autogenerated',
  //     dirName: 'faq',
  //   },
  // ],
}

export = sidebars
